name: robust-xai-medimg
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1
  - torchvision=0.16
  - torchaudio=2.1
  - cuda-toolkit=12.1
  - cudnn
  - pip:
      - timm==0.9.12
      - albumentations==1.3.1
      - qudida==0.0.4
      - opencv-python-headless==4.10.0.84
      - torchmetrics==1.5.1
      - captum==0.7.0
      - optuna==3.6.1
      - grad-cam==1.5.6
      - scikit-learn==1.7.2
      - pandas==2.3.3
      - matplotlib==3.9.2
      - seaborn==0.13.2
      - PyYAML==6.0.3
