name: robust-xai-medimg
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  # GPU stack from conda (one transaction avoids DLL mismatches)
  - pytorch=2.1
  - torchvision=0.16
  - torchaudio=2.1
  - pytorch-cuda=12.1  # pulls matching CUDA runtime/toolkit
  - pip
  - cudnn
  - numpy
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - pyyaml=6.0.3
  - pip:
      - timm==0.9.12
      - albumentations==1.3.1
      - qudida==0.0.4
      - opencv-python-headless==4.10.0.84
      - torchmetrics==1.5.1
      - captum==0.7.0
      - optuna==3.6.1
      - pytorch-grad-cam==1.5.2
